# This file provides instructions for packaging.

`Module-Quote`
	perl_version_from m`Module::Quote`;
	version_from      m`Module::Quote`;
	readme_from       m`Module::Quote`;
	test_requires     p`Test::More 0.61`;
	requires          p`Module::Hash 0.001`;
	requires          p`PerlX::QuoteOperator 0.004`;
.

